-- Add optional sector planning/export fields to devices.

ALTER TABLE devices
  ADD COLUMN IF NOT EXISTS radius_m DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS tech INTEGER,
  ADD COLUMN IF NOT EXISTS down_mbps DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS up_mbps DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS latency_ms DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS bizres VARCHAR(1);
